### Create a report (로그인 필요)
POST http://localhost:3000/reports
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInYiOjAsInR5cCI6ImFjY2VzcyIsImlhdCI6MTc1ODYyNzAzMiwiZXhwIjoxNzU4NjI3OTMyfQ.NYWJPb4mWioOhSaLJNpozHSkHGCZPsRqeFlX0U-aAUA

{
  "manufacturer": "Samsung",
  "model": "Galaxy S24",
  "screenSize": 6,
  "price": 1200000
}

### Get all reports (로그인 필요)
GET http://localhost:3000/reports/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInYiOjAsInR5cCI6ImFjY2VzcyIsImlhdCI6MTc1ODYyNzAzMiwiZXhwIjoxNzU4NjI3OTMyfQ.NYWJPb4mWioOhSaLJNpozHSkHGCZPsRqeFlX0U-aAUA

